INSERT INTO eye_bank(eyeBankShortName, eyeBankFullName, regionID)
VALUES
    ('AEBAP', 'Aravind Eye Bank Association of Pondicherry', 6),
    ('AIOB', 'Aravind - IOB Eye Bank', 6),
    ('CL Gupta', 'C. L. Gupta Eye Institute', 4),
    ('CUSEB', 'Sankara Nethralaya Chennai', 6),
    ('DDEB', 'Drushti Daan Eye Bank', 3),
    ('EBAK', 'Eye Bank Association of Kerala', 6),
    ('EBSR', 'Eye Bank Society Rajasthan', 1),
    ('GN', 'Gomabai Methralaya', 4),
    ('GNEC', 'Guru Nanak Eye Centre', 1),
    ('HVDEB', 'HV Desai Eye Bank', 5),
    ('IGIMS', 'Indira Gandhi Institute of Medical Sciences', 3),
    ('KGMU', 'KGMU UP Community Eye Bank', 4),
    ('LIEB', 'Lions International Eye Bank (aka Bangalore West Lions Super specialty Eye Hospital)', 6),
    ('NEB (AIIMS)', 'National Eye Bank', 1),
    ('Niramaya', 'Y.P. Mahindru Nirmaya Eye Bank', 1),
    ('PGI', 'Eye Bank Society of Chandigarh Eye Bank; PGIMER', 1),
    ('RAEB', 'Rotary Aravind Eye Bank', 6),
    ('RAIEB', 'Rotary Aravind International Eye Bank', 6),
    ('RIEB', 'Ramayamma International Eye Bank', 6),
    ('Sahiyara', 'Matoshree Gomtiben Ratanshree Chheda Sahiyara Eye Bank', 5),
    ('SCEH', 'Dr. Shroff''s Charity Eye Hospital', 1),
    ('SNC', 'Sadguru Nethra Chikitsalaya, Chitrakoot', 4),
    ('SNK', 'Sankara Nethralaya, Kolkata', 3);
